### ISSUE TITLE
Cerne do projeto

### ISSUE THREAD

**Issue by mattosvmp** [mattosvmp/projeto-rosario#6]
Eis aqui o print das razões de existir este projeto, contido no próprio projeto, veja por sí próprio (de alguma forma) um dos branchs que contém no código isso dentro de um `<p>` mesmo kkkkkk:
![Captura de tela de 2024-09-10 14-51-13](https://github.com/user-attachments/assets/2bdde351-2fd6-4633-be20-eb6e51913f33)

E para mostrar que eu fiquei viciado nessa questão escrever as tarefas no papel antes de digitalizar elas:
![WhatsApp Image 2024-09-10 at 14 48 59](https://github.com/user-attachments/assets/2c2db78b-dc70-4890-9422-352e0d7a2b1d)

**Comment by Silasns** [comment]
Que projeto massa man, espero pode ver ele pronto!! (Salve Maria)
